server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: qa

#  config:
#    import:
#      - "application_prod.yml"
#      - "application_qa.yml"
#  profiles:
#    active: "prod"
#
#build:
#  version: "1.0"
#
#cards:
#  message: "Welcome to DigiBank cards related local APIs "
#  contactDetails:
#    name: "Dragos Lech - Developer"
#    email: "dragos@eazybank.com"
#  onCallSupport:
#    - (412) 419-3491

management:
  endpoints:
    web:
      exposure:
        include: "*"