server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3309/cardsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  #  rabbitmq:
#    host: localhost
#    username: guest
#    password: guest
#    port: 5672
  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: qa

#  config:
#    import:
#      - "application_prod.yml"
#      - "application_qa.yml"
#  profiles:
#    active: "prod"
#
#build:
#  version: "1.0"
#
#cards:
#  message: "Welcome to DigiBank cards related local APIs "
#  contactDetails:
#    name: "Dragos Lech - Developer"
#    email: "dragos@eazybank.com"
#  onCallSupport:
#    - (412) 419-3491

management:
  endpoints:
    web:
      exposure:
        include: "*"