services:
  accounts:
    image: "moazzam21/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - myBankNetwork
  loans:
    image: "moazzam21/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - myBankNetwork
  cards:
    image: "moazzam21/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - myBankNetwork
networks:
  myBankNetwork:
    driver: "bridge"