server:
  port: 8090

spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  sql:
    init:
      mode: always
  #  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: qa
#  config:
#    import:
#      - "application_prod.yml"
#      - "application_qa.yml"
#  profiles:
#    active:
#      - "qa"
#
#build:
#  version: "1.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"