services:
  #  rabbit:
  #    image: rabbitmq:4-management
  #    hostname: rabbit
  #    ports:
  #      - "5672:5672"
  #      - "15672:15672"
  #    healthcheck:
  #      test: rabbitmq-diagnostics check_port_connectivity
  #      interval: 10s
  #      timeout: 5s
  #      retries: 10
  #      start_period: 5s
  #    extends:
  #      file: common-config.yml
  #      service: network-deploy-service

  configserver:
    image: "moazzam21/configserver:v5"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    #    depends_on:
    #      rabbit:
    #        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "moazzam21/eurekaserver:v5"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "moazzam21/accounts:v5"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  #  accounts_slave:
  #    image: "moazzam21/accounts:v5"
  #    container_name: accounts-ms-slave
  #    ports:
  #      - "8081:8080"
  #    healthcheck:
  #      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
  #      interval: 10s
  #      timeout: 5s
  #      retries: 10
  #      start_period: 10s
  #    depends_on:
  #      configserver:
  #        condition: service_healthy
  #      eurekaserver:
  #        condition: service_healthy
  #    environment:
  #      SPRING_APPLICATION_NAME: accounts
  #    extends:
  #      file: common-config.yml
  #      service: microservice-eureka-config

  loans:
    image: "moazzam21/loans:v5"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  #  loans_slave:
  #    image: "moazzam21/loans:v5"
  #    container_name: loans-ms-slave
  #    ports:
  #      - "8091:8090"
  #    healthcheck:
  #      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
  #      interval: 10s
  #      timeout: 5s
  #      retries: 10
  #      start_period: 10s
  #    depends_on:
  #      configserver:
  #        condition: service_healthy
  #      eurekaserver:
  #        condition: service_healthy
  #    environment:
  #      SPRING_APPLICATION_NAME: loans
  #    extends:
  #      file: common-config.yml
  #      service: microservice-eureka-config

  cards:
    image: "moazzam21/cards:v5"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  #  cards_slave:
  #    image: "moazzam21/cards:v5"
  #    container_name: cards-ms-slave
  #    ports:
  #      - "9001:9000"
  #    healthcheck:
  #      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
  #      interval: 10s
  #      timeout: 5s
  #      retries: 10
  #      start_period: 10s
  #    depends_on:
  #      configserver:
  #        condition: service_healthy
  #      eurekaserver:
  #        condition: service_healthy
  #    environment:
  #      SPRING_APPLICATION_NAME: cards
  #    extends:
  #      file: common-config.yml
  #      service: microservice-eureka-config

  gatewayserver:
    image: "moazzam21/gatewayserver:v5"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  myBankNetwork:
    driver: "bridge"



#################### Configuration withouth importing from common-config.yml ####################
#services:
#  rabbit:
#    image: rabbitmq:4-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    networks:
#      - myBankNetwork
#
#  configserver:
#    image: "moazzam21/configserver:v2"
#    container_name: configserver-ms
#    ports:
#      - "8071-8071"
#    depends_on:
#      rabbit:
#        condition: service_healthy
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - myBankNetwork
#
#  accounts:
#    image: "moazzam21/accounts:v2"
#    container_name: accounts-ms
#    ports:
#      - "8080:8080"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - myBankNetwork
#    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_APPLICATION_NAME: accounts
#
#  loans:
#    image: "moazzam21/loans:v2"
#    container_name: loans-ms
#    ports:
#      - "8090:8090"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - myBankNetwork
#    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_APPLICATION_NAME: loans
#
#  cards:
#    image: "moazzam21/cards:v2"
#    container_name: cards-ms
#    ports:
#      - "9000:9000"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - myBankNetwork
#    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_APPLICATION_NAME: cards
#networks:
#  myBankNetwork:
#    driver: "bridge"