  # ==============================================
  # Spring Boot Application Configuration File
  # File: application.yml
  # Purpose: Defines application name, database,
  # JPA/Hibernate behavior, H2 console, and server
  # ==============================================
  spring:
    # ----------------------------------------------
    # Application level configuration
    # ----------------------------------------------
    application:
      # Logical name of the Spring Boot application
      # Used in logs, monitoring, and Spring Cloud
      name: accounts
    profiles:
      active: prod
    config:
      import: "optional:configserver:http://localhost:8071/"
#    rabbitmq:
#      host: localhost
#      port: 5672
#      stream:
#        username: "guest"
#        password: "guest"
    # ----------------------------------------------
    # Datasource configuration (Database settings)
    # ----------------------------------------------
    datasource:
      # JDBC URL for H2 in-memory database
      # 'mem' means data is stored in RAM
      # 'testdb' is the database name
      url: jdbc:mysql://localhost:3307/accountsdb
      # Default username for H2
      username: root
      # Password for H2 (empty by default)
      password: root

    # ----------------------------------------------
    # JPA & Hibernate configuration
    # ----------------------------------------------
    jpa:
      # Prints SQL queries executed by Hibernate
      # Useful for debugging and learning
      show-sql: true
    sql:
      init:
        mode: always
  #
#    config:
#      import:
#        - "application_qa.yml"
#        - "application_prod.yml"
#
#    profiles:
#      active:
#        - "qa"

#
#
#  # ----------------------------------------------
#  # Server configuration
#  # ----------------------------------------------
#  server:
#    # Port on which embedded Tomcat server runs
#    port: 8080
#
#  build:
#    version: "3.0"
#
#  accounts:
#    message: "Welcome to DigiBank accounts related local APIs "
#    contactDetails:
#      name: "John Doe - Developer"
#      email: "john@digibank.com"
#    onCallSupport:
#      - (555) 555-1234
#      - (555) 523-1345

  management:
    endpoints:
      web:
        exposure:
          include: "*"