  spring:
    application:
      name: configserver
    profiles:
      active: git
    #      active: native
    cloud:
      config:
        server:
          git:
            uri: "https://github.com/moazzam-mahmood/spring-cloud-config.git"
            default-label: main
            timeout: 5
            clone-on-start: true
            force-pull: true
#    rabbitmq:
#      host: localhost
#      port: 5672
#      username: guest
#      password: guest
  #       native:
#           search-locations: "file:///C://Users//moazz//Documents//config"
#           search-locations: "classpath:/config"


  server:
   port: 8071

  encrypt:
    key: "124NHF2139CN2123E8CNX2EXZEJ"

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
    endpoint:
      health:
        probes:
          enabled: true